### ISSUE TITLE
user interface for certainty of property needs revamping

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#101]
My suggestion is can bee seen here: 

![image](https://cloud.githubusercontent.com/assets/4243679/22980578/3b41ff26-f39a-11e6-9632-038c88c71ae8.png)

**Comment by v1r0x** [comment]
I'd suggest this one:
![page-shot-2017-2-16 spacialist](https://cloud.githubusercontent.com/assets/9248714/23026712/6cfb98b0-f462-11e6-8d8c-11598f63cccb.png)
