### ISSUE TITLE
Not all entries saved when register new finds

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#11]
Some field work, but other don't:
- [X] 'Name', 'Aufbewahrungsort', 'Datierung' and 'Fundort': working
- [ ] 'beschrieben': only registers small pieces of text; behaves quite irregular
- [ ] 'Funddatum': doesn't work at all

**Comment by v1r0x** [comment]
'Funddatum' works fine for me.
Do you have an explicit for 'beschrieben'? It's hard to test something which
> only registers small pieces of text; behaves quite irregular
:wink:
