### ISSUE TITLE
Store user & project preferences in the DB

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#119]
Personal prefs should be persisted in the DB, including:
- [x] when a user changes the GUI langauge
- [x] when a user changes the column layouts

Project wide prefs should also be configurable and persisted in the DB:
- [x] the concept URL in thesaurus which is used as the root concept for tagging files in Spacialist
- [x] whether or not the geo map (or other part of the UI) shall be displayed. 
- [x] whether or not a link/button to the ThesauRex instance should be displayed
- [x] whether or not tooltips should be shall be displayed
- [x] Project name (displayed in the upper left corner and in ThesauRex URIs)

**Comment by v1r0x** [comment]
We should discuss a proper format/layout for the user data. And we should think about what prefs we want to save and how we could extend it in the future.

**Comment by derntl** [comment]
We store the prefs as a JSONB object in the DB for each user. 💯

**Comment by derntl** [comment]
Table with all possible settings: prefs (id, label, default_value)

Table linking user-specific values to a setting: user_prefs (pref_id, user_id, value)

Oder so ähnlich 🎱

**Comment by v1r0x** [comment]
> Project name (displayed in the upper left corner and in ThesauRex URIs)

The ThesauRex part obviously has to be done in ThesauRex. Will open an issue for it.
