### ISSUE TITLE
delete context does not work properly

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#140]
* when i delete a context from the "Delete" button in the context form, the context is deleted but it remains active in the form and stays in the tree (only after reload it is gone)

* when i delete a context from the tree right-click menu, i then cannot even click the "Delete" button in the modal popupt. Nothing happens at all.

**Comment by v1r0x** [comment]
I think I found the problem: `//$itemScope.remove(); TODO remove from list` :wink:
