### ISSUE TITLE
unlink context strange behavior

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#141]
1. when i click a map marker and click "unlink from context", the popup content does not change, although it has been unlinked. only when closing and clicking the marker again i see that it has been unlinked.

2. still, when clicking the already unlinked context in the tree, the marker popup goes up and displays the "This marker is not linked to any context" message.

**Comment by v1r0x** [comment]
I'll add this to #136

**Comment by derntl** [comment]
✔️
