### ISSUE TITLE
marker popup cannot indicate 2 or more linked contexts

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#150]
right now the heading in the popup displays one of the linked concepts. If mutliple contexts are linked to the marker, we need to allow individual unlinking

**Comment by v1r0x** [comment]
I talked to @dirkseidensticker and we discussed whether it should be possible to link one geo object to several contexts or not. We decided that it should be a 1:1 relation.

**Comment by derntl** [comment]
ok go ahead

**Comment by derntl** [comment]
I put this in issue #151
