### ISSUE TITLE
editing poligons and markers in map view

### ISSUE THREAD

**Issue by AngusLeBoeuf** [eScienceCenter/Spacialist#176]
editing of the poligons works fine. for analytical and representational reasons it would be great to change the colors of the polygons as to symbolize t.e. special buildings, streets, and so on. Also the possibility to change the form of markes, as we had it in the previous version, is no longer available but seems to be a helpfull feature to mark special concepts visually.

**Comment by v1r0x** [comment]
@Hvitgar is working on a branch to add color support for geodata objects. Unfortunately it is not possible to have both, color and shape for geo objects. We could either have color for polygons/lines and shape for markers or color for all. I think that a consistent system for all objects is better than one property for geo type A and another for geo type B.
