### ISSUE TITLE
Allow specify some target in URL

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#189]
Sharing a URL to some specific thing in Spacialist (e.g. the bibliography section, role management, or some selected context or marker) should be allowed.

**Comment by v1r0x** [comment]
I tried to fix this, but using `ui-router` is a pain in the a**. If anyone else wants to fix this: Feel free to continue on the `proper-links` branch.

**Comment by v1r0x** [comment]
FYI: Working on it with @Hvitgar on the new `ui-route` branch.
