### ISSUE TITLE
need to store original coordinates (+coord system)

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#191]
🎱

**Comment by v1r0x** [comment]
We need support for postgis `geometry` type. The postgis-plugin for Laravel/Lumen currently only supports `geography`. Someone opened a PR (based on Laravel 5.1, we have 5.3, latest version is 5.4), but nobody seems to care about it. We should think about a fork or anything else to get their PR merged.

**Comment by v1r0x** [comment]
As discussed we don't add the original data to the db, but add a preference where users/admins can set their SRID. This SRID is used as default for export and is displayed e.g in the marker popup.

**Comment by v1r0x** [comment]
This is fixed in the rewritten vuejs version. Testing is much appreciated.
