### ISSUE TITLE
Bibtex importer

### ISSUE THREAD

**Issue by v1r0x** [eScienceCenter/Spacialist#196]
Projects with an existing blbliography need some kind of importer. As bibtex is a widely used format and e.g. citavi can export bibtex files, we should at least have a bibtex importer.

**Comment by derntl** [comment]
This will probably require supporting more entry types. We should probably support all. https://en.wikipedia.org/wiki/BibTeX#Entry_types

**Comment by v1r0x** [comment]
Or we could ignore the other types and only import article, book, incollection and book.

**Comment by derntl** [comment]
Yes, but handling the ignorance of other types in the importer would be more demanding than extending `availableTypes` in the `literatureService`. I am happy to do this.

**Comment by v1r0x** [comment]
Then we should check if the other types have mandatory fields we don't have in the database right now. If you could extend the `availableTypes` and the database (if necessary), I'd implement the importer.

**Comment by derntl** [comment]
Just for the record, the following fields are missing:
* annote
* chapter
* crossref
* edition
* institution
* key
* month
* note
* organization
* school
* series

**Comment by v1r0x** [comment]
I'll add the importer in a new PR.
