### ISSUE TITLE
map enhancements

### ISSUE THREAD

**Issue by AngusLeBoeuf** [eScienceCenter/Spacialist#205]
Following enhancemantes would be great

- [x] change marker circles to 0.5 or 0.66 of current size
- [x] marker and polygons should get solid boarder lines in gray (#808080)
- [ ] show coordinates of object together with name when hovering
- [x] show coordinates in the popup
- [x] when creating a new marker show box to enter coordinates so that marker moves to new location - like in google maps

**Comment by dirkseidensticker** [comment]
> show coordinates of object together with name when hovering

I don't think we need this. It's sufficient to look up coordinates within the popup.
