### ISSUE TITLE
Drag & drop: moving an item downwards results in the item getting placed one position too far down

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#225]
### Steps to reproduce
see #214 

### Expected behaviour

Drag-drop should place items at the right position.

### Actual behaviour

Dragging an item within the tree upwards works as expected but moving an item downwards results in the item getting placed one position too far down.

Putting `#1` behind item `#2` to become the new `#2` results in it becoming `#3` (see Screenshot).

![c1ec2f6c-1eae-11e7-8169-878b96c180ed](https://cloud.githubusercontent.com/assets/6630811/25224043/80682030-25bd-11e7-915a-8b092aa5e92a.png)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Lumen Version:**

**Spacialist version:**

**List of activated modules:**
<details>
<summary>Module List</summary>
</details>

**Are you using external storage, if yes which one:** local/ftp/aws/...

### Client configuration
**Browser:**

**Operating system:**

#### Webserver error log
<details>
<summary>Webserver error log</summary>
```
Insert your webserver log here
```
</details>

#### Lumen log (lumen/storage/lumen.log)
<details>
<summary>Lumen log</summary>

```
Insert your Lumen log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by v1r0x** [comment]
I added this to delphi instead of backlog. Due to this bug the `rank` property of the tree elements is messed up.

**Comment by v1r0x** [comment]
Not part of the first 0.4 release, but definitely for 0.4.x.
