### ISSUE TITLE
Datatype epoc

### ISSUE THREAD

**Issue by DavidKi** [eScienceCenter/Spacialist#240]
### Steps to reproduce
1. Thesaurus: build a tree of names used for labeling time periods (like "neolithic")
2. Data Model Editor: Add a new attribute to the list of available attributes. Select the before builded tree of period names. As datatype select "Time Period and Epoch" and as parent element again the names of the period. Than add this attribute to an context.
3. Add a new context in the main window, select some content from the dropdown of the attribute you created before. Click save. 

### Expected behaviour
There should be be a pop-up telling, that the data has been saved

### Actual behaviour
Instead there is an error message: "Undefined property: stdClass::$start" The data has not been saved. The Browser Console is telling:
"store context <context-name>  mainService.js:286:9
Something went wrong...  app.js:803:17"

### Server configuration

**Operating system:** Ubuntu

**Web server:** Apache/2.4.18
</details>

### Client configuration
**Browser:** Firefox 53.0.3

**Operating system:** Windows 7 64 Bit

#### Browser log
<details>
<summary>Browser log</summary>

```
The network log
POST XHR https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/api/context/set [HTTP/1.1 500 Internal Server Error 179ms]
```
</details>

**Comment by v1r0x** [comment]
Hi David,

thanks for your report! I could reproduce your error. The current version expects not only a time period but also a start and end date which is not intended and a bug. But still, if you enter a start and end date and a period it is possible to store the data, but when you later try to load the data (click on the item) it throws an error.

I update the issue as soon as I have a working fix.
