### ISSUE TITLE
Datepicker and datatype date

### ISSUE THREAD

**Issue by DavidKi** [eScienceCenter/Spacialist#243]
### Steps to reproduce
1. Add a Attribute to a context in the Data Model Editor with type "Date Input" and a Name from Thesaurex
2. Adding a date into the new field (by typing or by clicking on the calender-icon)
3. Click the save button

### Expected behaviour
There should be a Pop-up telling that the data has been saved and when again opening the context the date should still be visible

### Actual behaviour
Pop-Up tells, that the data has been saved. But when reopening the context in Spacialist, there is nothing visible. When taking a look into the backend I can see, that the date is actually saved in the database in the attribute_values table. But it is only almost the correct date. When typing in the frontend 18.04.1915 in the backend is saved 1915-04-17. So every date gets one day older!

### Server configuration

**Operating system:** Ubuntu

**Web server:** Apache/2.4.18

**Lumen Version:** 5.3.3

### Client configuration
**Browser:**Firefox 54.0

**Operating system:** Windows 7 64 bit

#### Browser log
<details>
<summary>Browser log</summary>

```
Datepicker directive: "ng-model" value must be a Date object  angular.min.js:119:446
	f/< https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/bower_components/angular/angular.min.js:119:446
	this.render https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:7:24756
	this.init/p.$render https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:7:24599
	gh</< https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/bower_components/angular/angular.min.js:293:407
	$digest https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/bower_components/angular/angular.min.js:144:320
	$apply https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/bower_components/angular/angular.min.js:147:361
	l https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/bower_components/angular/angular.min.js:99:192
	K https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/bower_components/angular/angular.min.js:103:376
	tg/</N.onload https://escience-center.uni-tuebingen.de/spacialist/steinlachtal/bower_components/angular/angular.min.js:104:338
```
</details>

**Comment by v1r0x** [comment]
Hi David,

thanks again for your report.
Due to language mix (js and php) there were some problems with the timezones. The values should have been stored in `dt_val`not it in `str_val`. I removed the time so there should no longer be a problem with timezones. The values are now (in another branch currently) stored in the `dt_val` column.
You could have a look at the branch and check if it works or wait until we have merged it into the master branch. The latter option is definitely the easier one for you :wink:

**Comment by DavidKi** [comment]
I just have checked the new branch on my local machine. Seems like its working! Date is correctly stored and saved! Thanks for fixing @v1r0x
