### ISSUE TITLE
Adding list of linked contexts in photos popup

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#250]
The photos/file viewer popup should have a list of contexts that are linked with an individual photo/file. The related tab exists already. It might suffice to have a unsorted list.

May be functionally depend on #189

**Comment by v1r0x** [comment]
Doesn't depend on #189 
Everybody ok with an unsorted list? @eScienceCenter/spacialists

**Comment by derntl** [comment]
Surely.

**Comment by AngusLeBoeuf** [comment]
of course

**Comment by v1r0x** [comment]
Got fixed in #285
