### ISSUE TITLE
New attribute type: automatic identifier

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#258]
Anna (Saône) has suggested to add an attribute type that is filled automatically with a unique identifier when an instance of a context is created. This would be similar to the `serial` attribute type in postgres. Example: auto assignment of a unique Fundnummer in the field.

**Comment by derntl** [comment]
Same thing is needed in PotCat project

**Comment by v1r0x** [comment]
This is fixed in the rewritten vuejs version. Testing is much appreciated.
