### ISSUE TITLE
restrict thesaurus node descendants for single/multi-choice attributes

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#259]
It should be possible to limit the set of descendants of a node that feeds an single/multiple-choice dropdown box.  A first enhancement would be to allow the data model editor to choose between all descendants of the node or child nodes only. 

(A potential follow-up enhancement would be to allow the data model editor to select an arbitrary subset of the descendants.)

**Comment by v1r0x** [comment]
This is fixed in the rewritten vuejs version. Testing is much appreciated.
