### ISSUE TITLE
3D model upload 

### ISSUE THREAD

**Issue by AngusLeBoeuf** [eScienceCenter/Spacialist#261]
3D models larger than 50 MB can't be uploaded and an error message appears telling something went wrong.
Further more a loading screen should be implemented when opening a model. Especially some models are huge and take time to load.

**Comment by AngusLeBoeuf** [comment]
3D models larger than 50 MB can't be uploaded and an error message appears telling something went wrong.
Further more a loading screen should be implemented when opening a model. Especially some models are huge and take time to load.

**Comment by v1r0x** [comment]
It should be possible to upload files with a maximum size of 128MB. I reconfigured the server to allow 256MB files, but it seems that this doesn't work. We should think of a good cap for files. Any suggestions?

**Comment by AngusLeBoeuf** [comment]
128 MB may work for most of the models comming directly from Photoscan. After orientation in Blender the models might get bigger than 150 MB - so at least an upload up to 200 MB would be nice.
But I am also trying to find a way to decrease simply the size of the models.
