### ISSUE TITLE
Moving attributes in the Data Model Editor up and down seems to fail randomly

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#263]
e.g. in the Steinlachtal project

**Comment by derntl** [comment]
on ui-route (instance intern) select attribute dolores and try to move the bottom `et`  up -> fails

on master (instance demo/cannae) i was not able to reproduce it

**Comment by v1r0x** [comment]
> on ui-route (instance intern) select attribute dolores and try to move the bottom et up -> fails

It does work, but you won't see any difference in the ui, because the `RandomSeeder` in Lumen added the attribute `et` two times to the context.

**Comment by derntl** [comment]
click around a bit. at some point you cannot move "et" even though it would be distinguishable in the UI if it were moved

**Comment by derntl** [comment]
will be closed automatically when `ui-route` branch is merged
