### ISSUE TITLE
Edit attribute label button is dead

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#264]
In the Data Model Editor, hovering over an attribute shows an edit button that does nothing when clicked.

![image](https://user-images.githubusercontent.com/4243679/28670695-22e531ae-72da-11e7-940c-84dd70782b0a.png)

**Comment by v1r0x** [comment]
Should we add some logic to it or remove it?
Adding logic would lead to the question what should happen when the user switches the attribute type **or** if it should only be possible to assign a new label

**Comment by derntl** [comment]
If the button is dead, I would prefer to remove it.

**Comment by v1r0x** [comment]
But do we want such a button or not? If we want it, I think it is easier to implement it, then removing it...

**Comment by derntl** [comment]
Editing the datatype of an attribute comes with some potential problems, e.g. what happens to existing data? It feels simpler to remove the button for now 🔪

**Comment by v1r0x** [comment]
Is editing the datatype a feature we want or not? If not, we could add _edit label_ functionality to the button. If we want it, I'd suggest that we try to cast existing values to the new datatype (e.g. double to integer or string to stringf should be possible).

**Comment by derntl** [comment]
💯
