### ISSUE TITLE
Login fails with underprivileged user

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#289]
A user that has only view* persmissions cannot log in.

Console:
* `GET https://escience-center.uni-tuebingen.de/spacialist/intern/api/file` --> HTTP 403
* `GET https://escience-center.uni-tuebingen.de/spacialist/intern/api/overlay` --> HTTP 403
* Something went wrong ....
* `Transition Rejection($id: 1 type: 6, message: The transition errored, detail: {"data":{"error":"You do not have the permission to call this method`...

**Comment by Hvitgar** [comment]
Tested on 0.4.1: logged in as guest user with permissions 'view concepts', 'view photos', 'view geodata', 'view thesaurus concepts' and everything worked as expected. Feel free to reopen and comment if someone still has issues during log in.
