### ISSUE TITLE
Geodata Analysis

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#303]
Some minor things to add to the GIS-View:

## Importing Geodata
* [x] Preview (e.g. csv) should only show first 10 or so rows
* [x] In case a user has a file (csv) without a header row the header should be set to 0 (while 1 is the default). In that case the cols should be names like Var1 ... Var#

## Analysis of Geodata
* [x] Geodata should be styled (color and shape) according to attributes
* [x] Label should be added and editable (font, color, background)
* [ ] (Piechart overlay like in QGIS)

**Comment by v1r0x** [comment]
This is currently in development for the new vue version. Any testing/feedback is much appreciated.

**Comment by v1r0x** [comment]
Most of the individual parts have been fixed/added in the 0.7 giza release. Further development will be moved to the next release (helgö).

**Comment by dirkseidensticker** [comment]
👍
