### ISSUE TITLE
Header Bar

### ISSUE THREAD

**Issue by v1r0x** [eScienceCenter/Spacialist#306]
The current header bar has four parts, which are not completely consistent.
1. Spacialist Logo
2. Search Bar
3. Views (Data Analysis, Bibliography, (Data Import (`data-importer` branch))
4. Different Settings (+ a couple of views, which should be in the same place as 3.)
![header-bar](https://user-images.githubusercontent.com/9248714/33941486-20d85c28-e013-11e7-81d7-1fe41a833b2e.png)

I'd keep 1. and 2. as they are now, but I'm not happy with the 3. and 4. At least the GIS View should be in the same place as DA and Bibliography.
Adding GIS to 3. would fix that, but on smaller screens, this could lead to an ugly UI.

a. Move all views to dropdown next to the search bar and use sub menus for dropdown views (e.g. Data Analysis) and keep all settings (4.) as they are.
b. Keep the views as list in the header, but move the settings (4.) to a sidebar that can be toggled as overlay (as on smartphones)
c. ???

What do you think? a. or b.? Or any other idea? Please comment and add new ideas to the list.
@eScienceCenter/spacialists

**Comment by derntl** [comment]
Good point. I would put it into dropdown menus like this:

Tools
* GIS View
* Literature Manager
* Data Analysis
  * Analysis Builder
  * Stored Queries
* Data Import

Settings
* User Management
* Role Management
* Map Layers Editor
* Project Data Model
* Project Thesaurus (ThesauRex)
* User Preferences
* System Preferences

not 100% sure about ThesauRex. Also Data could be a dedicated menu

**Comment by v1r0x** [comment]
That's the new header bar. Submenus are not possible in bootstrap (anymore). Thus, I added the entries to different sections. Instead of sections we could use simple dividers, but that looks ugly with different entries with the same icon in a section (in our case the two data analysis entries). I also added ThesauRex to tools (as external tool), because it makes more sense to me. What do you think? Any better solution?

![header-bar](https://user-images.githubusercontent.com/9248714/33994407-abd5a7f0-e0da-11e7-9e45-d08aff045271.png)

**Comment by derntl** [comment]
looks goodly 💯  I would move dbWebGen to the External Tools section, and rename "Internal (BETA)" simply to "Data Analysis (beta)"

**Comment by v1r0x** [comment]
Multilevel dropdowns are no longer supported by bootstrap. Thus, moving it to the settings menu is no option. I'd keep it as top level to quickly switch between languages for other project partners. screenshots, ..., but I'm also ok with (re)moving it elsewhere.
What's your opinion @dirkseidensticker @AngusLeBoeuf ?

**Comment by v1r0x** [comment]
New version

![header-bar](https://user-images.githubusercontent.com/9248714/34048177-08e877b4-e1b3-11e7-8098-d6cfb45bf34f.png)

**Comment by dirkseidensticker** [comment]
Looks very good. A small detail: should the 'launch'-icon not be placed behind ThesauRex, like with dbWebGen?

**Comment by v1r0x** [comment]
Forgot to remove it from dbWebGen. It should only be in the header

**Comment by derntl** [comment]
👍

**Comment by v1r0x** [comment]
Closed by #316
