### ISSUE TITLE
Backup not possible -  bad permissions

### ISSUE THREAD

**Issue by DavidKi** [eScienceCenter/Spacialist#318]
### Steps to reproduce
1. store some query in the analysis-tool
2. backup your database: pg_dump  -h <host>  -U <user> -d <dbname> -f ~/backup.sql --inserts

### Expected behavior
Postgres should dump the DB according to the pg_dump settings one has chosen

### Actual behavior
No Backup is created. Error message: pg_dump: [archiver (db)] query failed: ERROR:  permission denied for relation stored_queries.
Because stored_queries is owned by postgres-user, Non-Superusers can't backup! 
Would be very useful, if every table is accessible by Non-Superusers (e.g.  with GRANT Syntax like in table spatial_ref_sys).

### Server configuration

**Operating system:** Ubuntu

**Web server:** Apache/2.4.18

**Database:** ??

**PHP version:** ??

**Lumen Version:** 5.3.3

**Spacialist version:** ??

**Comment by dirkseidensticker** [comment]
This is no Spacialist Issue but a wrong configuration of PostgeSQL. I just granted your DB user full rights on the `stored_queries` table, which should fix the issue.

@DavidKi : Please test and once ok close the issue.

**Comment by DavidKi** [comment]
With the new permissions backup works now. Thanks!
Just for clarification: How did I get this wrong configuration? Is the table stored_queries auto-generated when a analysis is stored? If yes, why with wrong permissions?

**Comment by v1r0x** [comment]
The table is auto-generated by the dbWebGen-Plugin. @derntl should know more about it.

**Comment by dirkseidensticker** [comment]
As I said, strictly speaking it's no Spacialist issue, it was triggered by a missing permission of your specific database user (not to be confused with a Spacialist user) on the DB itself and could only solved directly on the DB (pgAdmin). If `DB_USERNAME` in `lumen/.env` is the standard DB user, which has all permissions usually, this issue doesn't occur.

**Comment by DavidKi** [comment]
ok, thanks a lot for clarifying this!
