### ISSUE TITLE
Proposals for improvements in the UI

### ISSUE THREAD

**Issue by DavidKi** [eScienceCenter/Spacialist#322]
### Steps to reproduce
1. Add some sources to a contexts attribute
2. Add a comment to the source when adding the source

### Proposals:
1. The pop-up for adding the sources comes up in the middle of the screen and it is not possible to drag the pop-up to an other place (e.g. 2nd monitor). So one could not see the main window in behind. Would be nice to see the data when adding sources to them.

2. When a source has been added, the comment is not editable. Would be helpful, if one could edit it after adding the source.

**Comment by v1r0x** [comment]
Thanks for your proposals!

1. The current popup is a bootstrap modal, which is added to the HTML document. There are some jQuery-based solutions and maybe other (selfmade) hacks to achive a draggable modal, but that's not a good solution and is only draggable inside the HTML window. Another solution would be to open the modal as stand-alone popup in a new html window. That way you can move it anywhere (e.g. other monitors), but that breaks our "workflow" aka open all things in modals

My preferred solution would be a toggle to show/hide the modal, so you can check your data without closing the modal.

2. That's true. For now you have to add a comment before you add the source. Editing might be part of a later Federsee or Giza release.

**Comment by v1r0x** [comment]
FYI:
@Hvitgar and I are working on a rewrite of Spacialist using other/modern frameworks. Both of your proposals are implemented in the vuejs-test branch.
Limitation: The new modal plugin allows to drag the modal, but it is not possible to move it to another monitor (see last comment).

**Comment by v1r0x** [comment]
This is fixed in the rewritten vuejs version. Testing is much appreciated.
