### ISSUE TITLE
Remove geometry constraint

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#326]
At the moment the user needs to define a geometry type when creating a new context-type and he can not change this afterwards. This was only implemented with QGIS functionalities (or their lack of) in mind. Only due to the fact that QGIS can handle only one type of geometry per layer, this constraint was added.

Experience within the last month shows that it might be worth considering to roll back this decision. Regarding Spacialist this constraint is not necessary as neither the DB or Leaflet/Open Layers have constraints like that.

My proposal: remove the constraint to simplify the creation of geo-data.

Regarding export to shape functionality separate files can be created for each type of geometry. See QuickOSM Plugin for QGIS https://github.com/3liz/QuickOSM as reference. Within this plugin you query certain OSM layers and get three .shp files, one for each geometry back.

A direct connection of the DB to QGIS -- that we thought of initially -- needs specific queries anyhow. Those might include querying for specific geometries. But at the moment this direct connection seems not to be in use, while the constraint hinders the usability in a way.

**Comment by derntl** [comment]
I would not remove the geometry constraint functionality, but allow the user to omit setting a geometry constraint when creating a new context type. I agree that it should be possible to change the constraint.

**Comment by DavidKi** [comment]
I often connect directly from QGIS to the DB. When trying to load spatial data from the db in some situations occur problems due to the geometry-types.
But when the DB-Connection in QGIS is established, the default geodata-layer of Spacialist (and other optional spatial layers) is spitted into different tables. So I can easily load  points, polygons and lines separately, although they are stored in one table in Spacialist. 
Right now I don't see a problem when, the layers don't have one defined geometry-type. But I never used the shape export functionality...

**Comment by dirkseidensticker** [comment]
@DavidKi Thanks for your comment. Do I understand correctly that your are querying the DB and QGIS automatically creates individual 'virtual' tables for each geometry-type? That would reduce the necessity for a geometry constraint in Spacialist really to nothing and could be implemented at something rather optional as @derntl proposed.

**Comment by DavidKi** [comment]
@dirkseidensticker You're right! QGIS creates some kind of virtual table for each geometry! See the Screenshot below:
![postgis](https://user-images.githubusercontent.com/11569315/35211929-b4a97612-ff58-11e7-8d9e-7dbe3cb0f178.png)
I have polygons and points in Spacialist. QGIS offers me to load them in separate tables.
If I didn't miss something, I would agree with the proposal by @derntl

**Comment by v1r0x** [comment]
Praise QGIS!

IMO we should keep it as it is right now (and maybe add an option to leave the restriction blank) or remove it **completely**. Allow the user to modify it afterwards difficult to implement and I don't know what should happen if the user switches to another geometry.

**Comment by derntl** [comment]
👍 for leave as is with additional blank option (if easy to implement)

**Comment by dirkseidensticker** [comment]
@DavidKi many thanks for your clarification.

👍👍 For removing ist completely!!

**Comment by v1r0x** [comment]
Based on project requirements, we decided to keep the restriction, **but** add an option to allow all geometry types for a context-type. In addition, a context can be linked to several geo objects.

**Comment by dirkseidensticker** [comment]
Ok. What will be the default?

**Comment by v1r0x** [comment]
There is no _default_. You have to decide which one you want when you create a new context-type. The dropdown has no default option.

**Comment by dirkseidensticker** [comment]
:+1:

**Comment by v1r0x** [comment]
This is fixed in the rewritten vuejs version. Testing is much appreciated.
