### ISSUE TITLE
Give elements in the tree a background color

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#338]
Up to v0.6 the elements within the tree have been color coded according to their type. While the old implementation of coloring the text itself was problematic, we discussed in https://github.com/eScienceCenter/Spacialist/pull/331 that it might be better to have a colored background. While the current way (no colors) is very much clean, it is now harder to visually detect what entity you are looking for (without using the filters etc).

@eScienceCenter/spacialists What are the general opinions on bringing back the color coding (as background, not colored text) of entities within the tree?

**Comment by v1r0x** [comment]
The reasons I didn't add coloring were
1. Tree was too colorful
2. Hard to read if colors are too dark

To fix this, we could try to use a lightened version of the entity color as background and change the font color to black/white depending on the background color (https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color/3943023#3943023).

**Comment by v1r0x** [comment]
Here's three different styles for coloring:

1. **Highlighting Entity Type**
![spacialist-tree-type](https://user-images.githubusercontent.com/9248714/51487425-8b923380-1da3-11e9-8ca4-996df013a382.png)

2. **Highlighting Entity Name**
![spacialist-tree-name](https://user-images.githubusercontent.com/9248714/51487426-8b923380-1da3-11e9-8e98-04afe66c18e0.png)

3. **Use colored indicator**
![spacialist-tree-circle](https://user-images.githubusercontent.com/9248714/51487427-8c2aca00-1da3-11e9-84ba-b044a783fb7f.png)

What do you think @dirkseidensticker @eScienceCenter/spacialists ?

**Comment by derntl** [comment]
Actually only #2 would be feasible, because in most real DBs (see the ones we have) the entity type (#1) or the colored dot (#3) would be hidden due to limit width of the column.

**Comment by dirkseidensticker** [comment]
@v1r0x great proposals 👍 

I agree with @derntl that placing the color code is important. While going though the screenshots I thought about the No. 4 that @derntl is proposing: the dot should replace the icon (the little piller now) as it (the icon) has no real meaning without the distinction of finds and context, which has been removed rightfully. Thus the first visual distinction is prominent but not distracting and we lose a rather useless icon. So my vote is on No. 4 😄 

On a different but related note: might we consider to make it optional if the entity type is displayed after the entity name inside the tree using a yes/no field within the user preferences? Sometimes it annoys me a bit, as I know from the name with what I am dealing.

**Comment by derntl** [comment]
I think this looks good!

How is the color determined? Is it the same as the color of the layer linked to the entity type?

In a further step of Zukunftsmusik one could even think to allow users specify a custom unicode character or some fontawesome code/symbol for each entity type in the data model editor ;-)

**Comment by v1r0x** [comment]
> How is the color determined? Is it the same as the color of the layer linked to the entity type?

Yes, it's the layer color with an opacity of 50%.

**Comment by v1r0x** [comment]
I spent some time on @dirkseidensticker [suggestion](https://github.com/eScienceCenter/Spacialist/issues/338#issuecomment-456166330) and came up with a simplified version of the tree.

- The entity type is removed as it is represented by the colored dot
- The count of sub-entities moved to the front inside the colored dot (the `(xx)` looked misplaced). If an entity has no sub-entities, the dot is shown, a badge (in the same color) otherwise.

Here's a screenshot:
![spacialist-tree-badge-plus](https://user-images.githubusercontent.com/9248714/51682699-51fe3a00-1fe8-11e9-8cfc-84786701be97.png)


What do you think?

**Comment by dirkseidensticker** [comment]
I think it is very, very good. The entities without sub-entries are easily identifiable as well as those with child-entries. Listing the entity type behind the name is also no longer necessary as the coloring does the trick in differentiating and now with the entity type back into the form (see #337 ) ... from me 👍 👍

**Comment by derntl** [comment]
👍
