### ISSUE TITLE
Zeitspanne check constraint

### ISSUE THREAD

**Issue by DavidKi** [eScienceCenter/Spacialist#344]
### Steps to reproduce
1. Enter into an epoch field a starting date Before Christ and an ending date Before Christ
2. Add to both dates the "Before Christ" label 
3. Save your Edit

### Expected behaviour
It should report successful saving

### Actual behaviour
Reports error, that start date is after end date

Looks like some checking got confused with dates Before Christ

**Comment by v1r0x** [comment]
Which version of Spacialist do you use?

**Comment by DavidKi** [comment]
Don't know, its the "Neackaralb"-Project. In the about pop-up there is no Version shown up...

**Comment by v1r0x** [comment]
You are right. There was a missing check for dates where both start and end are BC. This should be fixed now.
The About popup should now also display the correct version.

Thank you for your report!
