### ISSUE TITLE
Move entities in entitiy tree

### ISSUE THREAD

**Issue by DavidKi** [eScienceCenter/Spacialist#345]
Could we make it possible to move an entity in the entity-tree from one Top-Level-Entity to another (Drag and Drop)?
Probably this could be difficult due to different attributes and may even lead to data loss.
But can we move one entity to another place in the tree on the same level (to another Top-Level-Entity) without changing the type of entity? See the example:

Original Layout
- Top 1

  - Sub 1

  - Sub 2

- Top 2

Modified Layout:
- Top 1

   - Sub 2

- Top 2

  - Sub 1

**Comment by v1r0x** [comment]
That's already possible, but only when sorting 'Rank - ascending (drag & drop)' is active (the first sorting icon above the tree).

When dragging an element over another element there is either
1. a red arrow icon (drop **not possible**)
2. a green arrow icon (drop **possible**)
  2.1 above the drop target: insert on same level **above** the target
  2.2 On drop target: insert as **child** of target
  2.3 below the drop target: insert on same level **below** the target
