### ISSUE TITLE
Max zoom level for map layers

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#351]
If there are only few closely colocated points, the map tries to zoom in up to a zoom level that is not served by maps like OSM. In the extreme case where there's only one point on the map, Spacialist requests zoom level 28. The map is empty then and one needs to zoom out 10 levels until a map tile shows up. Most publicly served maps don't go beyond zoom level 20,or even less. So in the layer configuration one should be able to set a max zoom level for each layer.

**Comment by DavidKi** [comment]
I ran into this problem once. It was a project with only a few or one geometrie(s). Users can get confused, when they don't see a map, even when they zoom a bit, it won't be enough to see anything. So a max (automated) zoom level can be a good idea. But perhaps under some circumstances users still want to zoom beyond level 20, so an manual zoom beyond level 20 should be available.

**Comment by v1r0x** [comment]
Fixed in the current 0.7.3/4 release branch. Will be released soon.
