### ISSUE TITLE
ThesauRex breaks down

### ISSUE THREAD

**Issue by ReKlug** [eScienceCenter/Spacialist#385]
### Description
After creating a few new entries i get the following message :GET Request api/v1/auth/refresh failed with status 429. 
I need to wait around 10 minutes to create the next entries, but again it breaks down after a few.

### Steps to reproduce
1. Creating new entries

**Spacialist version:** v0.7.3-giza

### Client configuration
**Browser:** firefox

**Comment by v1r0x** [comment]
Statuscode 429 stands for "Too Many Requests" and is returned when there are too many requests to the server in a given time. In the default configuration it is 60 requests per minute.
I increased it to 600 (which is the default in Spacialist). I hope that helps.

**Comment by ReKlug** [comment]
It works! Thank you
