### ISSUE TITLE
Data Analysis does not show integer Data

### ISSUE THREAD

**Issue by ReKlug** [eScienceCenter/Spacialist#386]
When analysing the Data, the result does not display integer Data. The Attribute field stays empty, althoug it contains information. If I change the attribute, using "S 900" instead of 900, the data is displayed.

### Description
Please describe your bug as precise as possible (e.g. including screensots or log files
![grafik](https://user-images.githubusercontent.com/79839740/112463345-683be800-8d62-11eb-9710-245050333411.png)
)

### Expected behaviour
The data should be displayed if integer or text. Sure, I can wirte "Sondage 900" instead of "900", but in other cases it may not be possible to change the type.

**Comment by v1r0x** [comment]
Please use the issue tracker of the [Analysis Tool](https://github.com/eScienceCenter/SpacialistDataAnalyzer) repo. Thank you!
