### ISSUE TITLE
Error when moving entities in the tree

### ISSUE THREAD

**Issue by ReKlug** [eScienceCenter/Spacialist#388]
When trying to move one Entity from one Top Level Entity to another, I get an Error message (PATCH Request api/v1/entity/6/rank failed with status 500. )
-->
### Steps to reproduce
1. The Entity "Rifriscolaro Grab R21-24" (Entitytype: Fundstelle) is located under the Entity "Place Rifriscolaro Grab R21-24"
2. I tried to move the Entity to "Place Rifriscolaro"
3. Result: error message

### Expected behaviour
The Entity should be now located under "Place Rifriscolaro"

### Actual behaviour
Error Message and the location does not change.
<img width="960" alt="entity verschieben" src="https://user-images.githubusercontent.com/9248714/120800256-05c04e80-c540-11eb-994c-d2d4a7f755b2.png">

Spacialist version: v0.7.3-giza

**Comment by v1r0x** [comment]
This was a problem in the database and has been fixed. Thanks for your report
