### ISSUE TITLE
Photos are not displayed

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#64]
Currently there are no photos displayed, however there are photos in the DB.

**Comment by v1r0x** [comment]
There was an image stored in the database (and linked), but was not present on the filesystem (`gui-screwed.jpg`). I uploaded a couple of other images and everything worked fine. Maybe there was something wrong with this particular image? @eScienceCenter/spacialists

**Comment by AngusLeBoeuf** [comment]
Still not working - no pics visible.
After uploading a picture from folder-path I get kicked and have to sign in again and still the pic is not there...

**Comment by AngusLeBoeuf** [comment]
in some very few cases uploading works but editing of the properties is impossible - the are tagged by some random information from the very beginning stage of spacialist...

**Comment by v1r0x** [comment]
Closing this in favor of #74
