### ISSUE TITLE
Queries are not selectable

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#76]
The popup that contained the different queries doesn't contain any items. Therefore it's impossible to query the database.

**Comment by v1r0x** [comment]
It also doesn't work if you open the query interface. I had to remove the (manually) added views. IMO we should think of a better solution. The old implementation was a quick&dirty solution for a meeting. What do you think @eScienceCenter/spacialists ?

**Comment by derntl** [comment]
The reason is that some views got lost in the database (e.g. the "german_attributes" view and others). This seems related to #44, should be part of migrations

**Comment by v1r0x** [comment]
The views we had were very specific. Not every project needs a `german_attributes` view. Thus I'm not sure if/how this should be a part of the migrations. But if we need just something that works (for now), I could re-add the view in pgAdmin and later discuss a better solution.

**Comment by derntl** [comment]
yes please re-add the view(s) for now. we can discuss alternatives later on

**Comment by v1r0x** [comment]
I re-added the views, but since our db layout has changed, we have to adjust the views as well. Hence we should definitely find a better solution.

**Comment by v1r0x** [comment]
Views work like a charm

**Comment by derntl** [comment]
🎱
