### ISSUE TITLE
Literature table should have a head that let's you reset the order or filter each column

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#77]
Currently the table that shows all literature within the project is sorted randomly and the can't be changed. It would be convenient to order every column individually and set customized filters; much like the tables within the Query tool worked.

**Comment by v1r0x** [comment]
What exactly do we need?
- sort asc/desc
- filter (filter all columns ("display all rows where any column matches the search term") or specific column ("display all rows where column XY matches the search term"))
- ... anything else?

@eScienceCenter/spacialists

**Comment by derntl** [comment]
We need to stay simple on this unless it is requested externally. Sorting is enough. Searching can be done using the browser.
