### ISSUE TITLE
Map-Tab

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#78]
- [x] It's not possible to link a geometry (a geo object) with a context from the database. This should be possible, very much like the way photos are linked with contexts.
- [x] Currently child-context are inheriting the geodata of their parent-contexts. This should not be the case. Like that only the topmost marks on the map can be selected, which are the child-elements usually.
- [x] During the first loading of the map, the center point of the Popups are way off. Only after panning or zooming around, the Popups are centered on top the their respective markers. This should be fixed.
- [x] When selecting a marker, the Popup is centered on the point one has clicked, not the center of the marker (which should be the case).
- [x] The legend should be as wide, as the longest label. Currently 'Architektureinheiten' are cut off and placed in a new line.
- [x] There should be a Layer-Selection that gives the user the ability to switch between different background maps and enable layers provided through the GeoServer (WMS)

**Comment by v1r0x** [comment]
> Currently child-context are inheriting the geodata of their parent-contexts. This should not be the case. Like that only the topmost marks on the map can be selected, which are the child-elements usually.

This is not correct. This was a bug in an old version and is already fixed. It only happens for elements created before the bug was fixed.

**Comment by v1r0x** [comment]
> It's not possible to link a geometry (a geo object) with a context from the database. This should be possible, very much like the way photos are linked with contexts.

Any idea how we should implement this in the UI?

**Comment by dirkseidensticker** [comment]
I would suggest that we put this into the pop-up window, which by the way should be collapsed by default. I'll suggest a new button that 'gives the magic' :smile:
