### ISSUE TITLE
Spacialist should share project database with ThesauRex

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/Spacialist#97]
For any specific project, both Spacialist and ThesauRex should use the same project DB

**Comment by v1r0x** [comment]
The current database layouts differ in one column. The thesaurex layout has one additional column `is_top_concept` which is set to `true` if either `hasTopConcept` or `topConceptOf` is present in the xml file **or** if a concept inside the tree is moved to the base level **or** if the user creates a new top concept.
The question is: Should we add the column to the spacialist layout as well or should we remove the column from thesaurex and substitute it with `is_top_concept = hasBroaders(concept);` ('current concept is top concept if it has broaders')? Please comment @eScienceCenter/spacialists

**Comment by derntl** [comment]
it depends whether `!hasBroaders(concept);` is expensive to compute or needs to be called very often. If it is, we should have the column in both DBs. If it isn't, the column is not really needed.
